export const initialState = {
  currencyState: [{
    currency: [{
      id: 1,
      last: 0,
      type: 'UAH',
      toFixed: 2,
      name: 'uah',
      visible: false,
      percentChange: 0,
      publicFirst: 'USD',
      publicSecond: 'UAH',
      firstCurrency: 'START',
      secondCurrency: 'BTCD'
    }, {
      id: 2,
      last: 0,
      type: 'RUB',
      toFixed: 2,
      name: 'rub',
      visible: false,
      percentChange: 0,
      publicFirst: 'USD',
      publicSecond: 'RUB',
      firstCurrency: 'START',
      secondCurrency: 'BTCD'
    }, {
      id: 3,
      last: 0,
      type: 'USDT_BTC',
      toFixed: 2,
      name: 'btc',
      visible: true,
      percentChange: 0,
      publicFirst: 'BTC',
      publicSecond: 'USD',
      firstCurrency: 'BTC',
      secondCurrency: 'START'
    }, {
      id: 4,
      last: 0,
      type: 'USDT_ETH',
      toFixed: 2,
      name: 'eth-dol',
      visible: true,
      percentChange: 0,
      publicFirst: 'ETH',
      publicSecond: 'USD',
      firstCurrency: 'ETH-alt',
      secondCurrency: 'START'
    }, {
      id: 5,
      last: 0,
      type: 'BTC_ETH',
      toFixed: 8,
      name: 'eth-btc',
      visible: true,
      percentChange: 0,
      publicFirst: 'ETH',
      publicSecond: 'BTC',
      firstCurrency: 'ETH-alt',
      secondCurrency: 'BTC'
    }, {
      id: 6,
      last: 0,
      type: 'BTC_ETC',
      toFixed: 8,
      name: 'etc-btc',
      visible: true,
      percentChange: 0,
      publicFirst: 'ETC',
      publicSecond: 'BTC',
      firstCurrency: 'ETH-alt',
      secondCurrency: 'BTC'
    }, {
      id: 7,
      last: 0,
      type: 'BTC_LSK',
      toFixed: 8,
      name: 'lisk',
      visible: true,
      percentChange: 0,
      publicFirst: 'LISK',
      publicSecond: 'BTC',
      firstCurrency: 'LISK-alt',
      secondCurrency: 'BTC'
    }, {
      id: 8,
      last: 0,
      type: 'BTC_DASH',
      toFixed: 8,
      name: 'DASH',
      visible: false,
      percentChange: 0,
      publicFirst: 'DASH',
      publicSecond: 'BTC',
      firstCurrency: 'DASH',
      secondCurrency: 'BTC'
    }, {
      id: 9,
      last: 0,
      type: 'BTC_LTC',
      toFixed: 8,
      name: 'litecoin',
      visible: false,
      percentChange: 0,
      publicFirst: 'Litecoin',
      publicSecond: 'BTC',
      firstCurrency: 'LTC',
      secondCurrency: 'BTC'
    }, {
      id: 10,
      last: 0,
      type: 'BTC_DOGE',
      toFixed: 8,
      name: 'dogecoin',
      visible: false,
      percentChange: 0,
      publicFirst: 'Dogecoin',
      publicSecond: 'BTC',
      firstCurrency: 'DOGE',
      secondCurrency: 'BTC'
    }, {
      id: 11,
      last: 0,
      type: 'BTC_NXT',
      toFixed: 8,
      name: 'nxt',
      visible: false,
      percentChange: 0,
      publicFirst: 'NXT',
      publicSecond: 'BTC',
      firstCurrency: 'NXT',
      secondCurrency: 'BTC'
    }, {
      id: 12,
      last: 0,
      type: 'BTC_XMR',
      toFixed: 8,
      name: 'monero',
      visible: false,
      percentChange: 0,
      publicFirst: 'Monero',
      publicSecond: 'BTC',
      firstCurrency: 'XMR',
      secondCurrency: 'BTC'
    }, {
      id: 13,
      last: 0,
      type: 'BTC_XRP',
      toFixed: 8,
      name: 'Ripple',
      visible: false,
      percentChange: 0,
      publicFirst: 'Ripple',
      publicSecond: 'BTC',
      firstCurrency: 'XRP',
      secondCurrency: 'BTC'
    }],
    rates: {}
  }],
  timeState: [{
    time: 0,
    date: 0,
    time24: true,
    localeRu: true
  }],
  configState: {
    interval: 30000,
    bgChannel: 237739,
    btc: 0,
    eth: 0
  }
}
